defmodule JIT do
  @doc """
  Generates a new Elixir module AST with a custom `__using__/1` macro and transformed function definitions.

  ## Parameters

    - `header`: The module header AST, typically an `{:__aliases__, _, [module_name]}` tuple representing the module name.
    - `body`: The body of the module, which can be a single definition or a block of definitions.

  ## Returns

    - An Elixir quoted expression (`quote`) that defines a new module with:
      - A `__using__/1` macro that invokes `JIT.process_module/2` with the module name and original body.
      - The transformed function definitions generated by `gen_new_definitions/1`.
  """
  def gen_new_module(header, body) do
    new_body =
      case body do
        {:__block__, [], definitions} -> gen_new_definitions(definitions)
        _ -> gen_new_definitions([body])
      end

    {:__aliases__, _, [module_name]} = header

    # Here, we create a `__using__/1` macro that will be injected into the new module.
    # This macro will call `JIT.process_module/2` with the module name and the original
    # body of the module. It is used if the user wants to include the module in another
    # module using `use`.
    using =
      quote do
        defmacro __using__(_opts) do
          JIT.process_module(unquote(module_name), unquote(Macro.escape(body)))
        end
      end

    new_module =
      quote do
        defmodule unquote(header) do
          unquote([using | new_body])
        end
      end

    new_module
  end

  # ------ Helper functions to generate new definitions for the module ------

  defp gen_new_definitions([]), do: []

  defp gen_new_definitions([{:include, _, _para} | t]) do
    gen_new_definitions(t)
  end

  defp gen_new_definitions([{:defd, _, [header, _code]} | t]) do
    {fname, comp_info, para} = header

    para =
      para
      |> Enum.map(fn {p, b, c} -> {String.to_atom("_" <> to_string(p)), b, c} end)

    new_code =
      quote do:
              def(unquote({fname, comp_info, para}),
                do: raise("A device function can only be called by kernels!")
              )

    [new_code | gen_new_definitions(t)]
  end

  defp gen_new_definitions([{:defk, _, [header, _code]} | t]) do
    {fname, comp_info, para} = header

    para =
      para
      |> Enum.map(fn {p, b, c} -> {String.to_atom("_" <> to_string(p)), b, c} end)

    new_code =
      quote do:
              def(unquote({fname, comp_info, para}),
                do: raise("A kernel can only be executed with spawn!")
              )

    [new_code | gen_new_definitions(t)]
  end

  defp gen_new_definitions([h | t]) do
    # IO.inspect h
    [h | gen_new_definitions(t)]
  end

  # ------ Helper functions to preprocess parameters and generate parameter strings for code generation ------

  # Preprocesses the formal parameters of a function by extracting the variable names from the tuples in the list. It returns a list of variable names as atoms.
  defp preprocess_formal_parameters(formal_para) do
    formal_para
    |> Enum.map(fn {p, _, _} -> p end)
  end

  # Receives a preprocessed list of parameters and a map of inferred types. Returns a string
  # representing the parameter list in the target code, where each parameter is represented by its type and name.
  defp get_param_str(processed_para, inf_types) do
    processed_para
    |> Enum.map(fn p -> PolyHok.backend().gen_para(p, Map.get(inf_types, p)) end)
    |> Enum.filter(fn p -> p != nil end)
    |> Enum.join(", ")
  end

  # Receives a preprocessed list of parameters and returns a list containing the variable names.
  defp get_param_vars(processed_para) do
    processed_para
    |> Enum.map(fn p -> p end)
  end

  @doc """
  Compiles a function or anonymous function into target code.
  ## Parameters
    - `func`: A tuple representing the function to compile. It can be either:
      - `{:anon, lambda_name, {fun_ast, inner_funs}, type_signature}` for anonymous functions.
      - `{name, type}` for named functions.
    - `compiled_funs`: A MapSet of already compiled functions to avoid recompiling functions that were already generated.
  ## Returns
    - A tuple of format {generated_code, updated_compiled_funs} where:
      - `generated_code` is a list of strings containing the generated code for the function and all the functions it calls (if they were not already compiled).
      - `updated_compiled_funs` is the updated MapSet of compiled functions including the current function.
  """
  def compile_function({:anon, lambda_name, {fun_ast, _inner_funs}, type_signature}, compiled_funs) do
    delta = gen_delta_from_type(fun_ast, type_signature)

    inf_types =
      case infer_types(fun_ast, delta, lambda_name) do
        {:ok, types} ->
          types

        {:error, _types, reason} ->
          raise "Type inference failed for anonymous function #{lambda_name}: #{reason}"
      end

    {:fn, _, [{:->, _, [para, body]}]} = fun_ast

    para = preprocess_formal_parameters(para)
    param_str = get_param_str(para, inf_types)
    param_vars = get_param_vars(para)

    fun_type = Map.get(inf_types, :return)

    code_body = PolyHok.backend().gen_code(body, inf_types, param_vars, "module", MapSet.new())

    function = PolyHok.backend().declare_function(lambda_name, param_str, code_body, fun_type)
    function = "\n" <> function <> "\n\n"

    {[function], compiled_funs}
  end

  def compile_function({name, type}, compiled_funs) do
    # Checks if the function was already compiled, if it was, we return an empty string and the same set of compiled functions
    if MapSet.member?(compiled_funs, name) do
      {[], compiled_funs}
    else
      nast = PolyHok.load_ast(name)

      case nast do
        nil ->
          [""]

        {fast, fun_graph} ->
          delta = gen_delta_from_type(fast, type)

          inf_types =
            case infer_types(fast, delta, name) do
              {:ok, types} ->
                types

              {:error, _types, reason} ->
                raise "Type inference failed for device function #{name}: #{reason}"
            end

          {:defd, _iinfo, [header, [body]]} = fast
          {fname, _, para} = header

          para = preprocess_formal_parameters(para)
          param_str = get_param_str(para, inf_types)
          param_vars = get_param_vars(para)

          fun_type = Map.get(inf_types, :return)

          fun_type =
            if fun_type == :unit do
              :void
            else
              fun_type
            end

          code_body =
            PolyHok.backend().gen_code(
              body,
              inf_types,
              param_vars,
              "module",
              MapSet.new()
            )

          function = PolyHok.backend().declare_function(fname, param_str, code_body, fun_type)
          function = "\n" <> function <> "\n\n"

          # Mark itself as compiled in the set of compiled functions
          compiled_funs = MapSet.put(compiled_funs, name)

          # Generate code for the functions called by the current function as well,
          # but only if they were not already generated
          other_funs =
            fun_graph
            |> Enum.map(fn x -> {x, inf_types[x]} end)
            |> Enum.filter(fn {f_name, types} ->
              types != nil and not MapSet.member?(compiled_funs, f_name)
            end)

          {code, compiled_funs} =
            Enum.reduce(other_funs, {[], compiled_funs}, fn fun, {code_acc, compiled_funs_acc} ->
              {new_code, compiled_funs_acc} = compile_function(fun, compiled_funs_acc)
              {code_acc ++ new_code, compiled_funs_acc}
            end)

          # Returns the generated code and the updated set of compiled functions
          {code ++ [function], compiled_funs}
      end
    end
  end

  @doc """
  Compiles a kernel definition into target code.

  ## Parameters

    - `kernel_ast`: The abstract syntax tree (AST) of the kernel definition.
    - `inf_types`: A map where keys are variable names and values are their inferred types.
    - `subs`: A map of formal parameters that are functions mapped to their actual names in target code.
  ## Returns
    - A string containing the generated code for the kernel.
  """
  def compile_kernel({:defk, _, [header, [body]]}, inf_types, subs) do
    {fname, _, para} = header

    para = preprocess_formal_parameters(para)
    param_str = get_param_str(para, inf_types)
    param_vars = get_param_vars(para)

    code_body = PolyHok.backend().gen_code(body, inf_types, param_vars, "module", subs)

    kernel = PolyHok.backend().declare_kernel(fname, param_str, code_body)

    "\n" <> kernel <> "\n\n"
  end

  #############################################################
  ###############################
  ##########
  ############  BEGIN CLOSURE ELIMINATION
  ############
  ################

  def closure_elimination(kast, l) do
    ###### process closure
    ##### adds extra parameters to kernels
    ####  adds extra arguments to closure calls
    ###   adds extra arguments to the kernel call
    #############
    if contains_closure(l) do
      # IO.puts "yooooooooooooooooooooooooo"
      map_extra_args = JIT.gen_map_fun_name_to_extra_para(kast, l)
      # IO.inspect map_extra_args
      kast = JIT.add_extra_closure_args(map_extra_args, kast)
      # IO.inspect kast
      # raise "hrell"
      kast = JIT.add_extra_closure_param(kast, l)
      l = JIT.add_extra_args_from_closures(l)
      {kast, l}
    else
      {kast, l}
    end
  end

  def contains_closure([]), do: false
  def contains_closure([{:closure, _name, _ast, _cargs, _cvalues} | _lt]), do: true
  def contains_closure([_a | lt]), do: contains_closure(lt)

  #########  creates a map from function arguments to the kernel to their extra parameters

  def gen_map_fun_name_to_extra_para({:defk, _info, [header, [_body]]}, l) do
    {_fname, _info_header, para} = header

    param_vars =
      para
      |> Enum.map(fn {p, _, _} -> p end)

    Map.new(gen_map_to_extra_para(param_vars, l))
  end

  defp gen_map_to_extra_para([], []) do
    []
  end

  defp gen_map_to_extra_para([para | tpara], [{:closure, _name, _ast, cargs, _cvalues} | targ]) do
    # extra_args = Enum.map(cargs,fn p -> {p,[],nil} end)

    [{para, cargs} | gen_map_to_extra_para(tpara, targ)]
  end

  defp gen_map_to_extra_para([_para | tpara], [_arg | targ]) do
    gen_map_to_extra_para(tpara, targ)
  end

  defp gen_map_to_extra_para(_p, _a) do
    raise "Kernel is receiving a list or arguments with the wrong size!"
  end

  #### adds extra closure parameters to kernel parameters

  def add_extra_closure_param({:defk, info, [header, [body]]}, l) do
    {fname, info_header, para} = header
    new_param_list = gen_extra_closure_param(para, l)
    {:defk, info, [{fname, info_header, new_param_list}, [body]]}
  end

  defp gen_extra_closure_param([], []) do
    []
  end

  defp gen_extra_closure_param([para | tpara], [{:closure, _name, _ast, cargs, _cvalues} | targ]) do
    extra_args = Enum.map(cargs, fn p -> {p, [], nil} end)

    [para | extra_args] ++ gen_extra_closure_param(tpara, targ)
  end

  defp gen_extra_closure_param([para | tpara], [_arg | targ]) do
    [para | gen_extra_closure_param(tpara, targ)]
  end

  defp gen_extra_closure_param(_p, _a) do
    raise "Kernel is receiving a list or arguments with the wrong size!"
  end

  ####### adds extra arguments from closures to the list of arguments of
  ####### kernel and substitute closures by anonymous functions

  def add_extra_args_from_closures([]), do: []

  def add_extra_args_from_closures([{:closure, name, ast, _cargs, cvalues} | targ]) do
    [{:anon, name, ast} | cvalues] ++ add_extra_args_from_closures(targ)
  end

  def add_extra_args_from_closures([arg | targ]) do
    [arg | add_extra_args_from_closures(targ)]
  end

  ##################### FIND FREE VARIABLES ##############################
  #################################################################

  def find_free_vars({:fn, _, [{:->, _, [para, body]}]}) do
    # IO.puts "para"
    # IO.inspect para
    # raise "hell"
    param_vars =
      para
      |> Enum.map(fn {p, _, _} -> p end)
      |> MapSet.new()

    # IO.inspect "body #{inspect body}"
    {_bound, free} = find_free_vars_body({param_vars, MapSet.new()}, body)
    # IO.puts "Bound"
    # IO.inspect bound
    # IO.puts "Free"
    # IO.inspect free
    MapSet.to_list(free)
  end

  def find_free_vars_body(map, body) do
    case body do
      {:__block__, _, _code} ->
        find_free_vars_block(map, body)

      {:do, {:__block__, pos, code}} ->
        find_free_vars_block(map, {:__block__, pos, code})

      {:do, exp} ->
        # IO.inspect "here #{inspect exp}"
        find_free_vars_command(map, exp)

      {_, _, _} ->
        find_free_vars_command(map, body)
    end
  end

  defp find_free_vars_block(map, {:__block__, _info, code}) do
    Enum.reduce(code, map, fn x, acc -> find_free_vars_command(acc, x) end)
  end

  defp find_free_vars_command(map, code) do
    # IO.inspect "here2"
    case code do
      {:for, i, [param, [body]]} ->
        find_free_vars_for(map, {:for, i, [param, [body]]})

      {:do_while, _i, [[doblock]]} ->
        find_free_vars_body(map, doblock)

      {:do_while_test, _i, [exp]} ->
        find_free_vars_exp(map, exp)

      {:while, _i, [bexp, [body]]} ->
        map = find_free_vars_exp(map, bexp)
        find_free_vars_body(map, body)

      # CRIAÇÃO DE NOVOS VETORES
      {{:., _i1, [Access, :get]}, _i2, [{var, _, nil}, size]} ->
        {bound, free} = map
        bound = MapSet.put(bound, var)
        find_free_vars_exp({bound, free}, size)

      {:__shared__, _i1, [{{:., _i2, [Access, :get]}, _i3, [{var, _, nil}, size]}]} ->
        {bound, free} = map
        bound = MapSet.put(bound, var)
        find_free_vars_exp({bound, free}, size)

      # assignment
      {:=, _i1, [{{:., _i2, [Access, :get]}, _i3, [{array, _i4, _arag}, acc_exp]}, exp]} ->
        {bound, free} = map

        if MapSet.member?(bound, array) do
          map
          |> find_free_vars_exp(acc_exp)
          |> find_free_vars_exp(exp)
        else
          {bound, MapSet.put(free, array)}
          |> find_free_vars_exp(acc_exp)
          |> find_free_vars_exp(exp)
        end

      {:=, _i, [{var, _, nil}, exp]} ->
        {bound, free} = map

        {MapSet.put(bound, var), free}
        |> find_free_vars_exp(exp)

      {:if, _i, if_com} ->
        find_free_vars_if(map, if_com)

      {:var, _i1, [{var, _i2, [{:=, _i3, [{_type, _ii, nil}, exp]}]}]} ->
        {bound, free} = map

        {MapSet.put(bound, var), free}
        |> find_free_vars_exp(exp)

      {:var, _i1, [{var, _i2, [{:=, _i3, [_type, exp]}]}]} ->
        {bound, free} = map

        {MapSet.put(bound, var), free}
        |> find_free_vars_exp(exp)

      {:var, _i1, [{var, _i2, [{_type, _i3, _t}]}]} ->
        {bound, free} = map
        {MapSet.put(bound, var), free}

      {:var, _i1, [{var, _i2, [_type]}]} ->
        {bound, free} = map
        {MapSet.put(bound, var), free}

      {:type, _i1, [{_var, _i2, [{_type, _i3, _t}]}]} ->
        map

      {:type, _i1, [{_var, _i2, [_type]}]} ->
        map

      {:return, _i, [arg]} ->
        #     IO.inspect "Aqui3"
        find_free_vars_exp(map, arg)

      {_fun, _info, args} when is_list(args) ->
        #    IO.inspect "Aqui3 #{length args} #{inspect fun}"
        Enum.reduce(args, map, fn x, acc -> find_free_vars_exp(acc, x) end)

      # raise "funcao: #{inspect fun}"
      #   {args,funs} = map
      #   if MapSet.member?(args,fun) do
      #     map
      #   else
      #      {args,MapSet.put(funs,fun)}
      #   end
      number when is_integer(number) or is_float(number) ->
        raise "Error: #{inspect(number)} is a command"

      c ->
        raise "Found unknown command (#{inspect(c)}) while searching for free vars."
    end
  end

  defp find_free_vars_for({bound, free}, {:for, _, [header, [body]]}) do
    case header do
      {:in, _, [{var, _, nil}, {:range, _, [n]}]} ->
        {bound, free} =
          {MapSet.put(bound, var), free}
          |> find_free_vars_exp(n)
          |> find_free_vars_body(body)

        {MapSet.delete(bound, var), free}

      {:in, _, [{var, _, nil}, {:range, _, [arg1, arg2]}]} ->
        {bound, free} =
          {MapSet.put(bound, var), free}
          |> find_free_vars_exp(arg1)
          |> find_free_vars_exp(arg2)
          |> find_free_vars_body(body)

        {MapSet.delete(bound, var), free}

      {:in, _, [{var, _, nil}, {:range, _, [arg1, arg2, step]}]} ->
        {bound, free} =
          {MapSet.put(bound, var), free}
          |> find_free_vars_exp(arg1)
          |> find_free_vars_exp(arg2)
          |> find_free_vars_exp(step)
          |> find_free_vars_body(body)

        {MapSet.delete(bound, var), free}
    end
  end

  defp find_free_vars_if(map, [bexp, [do: then]]) do
    map
    |> find_free_vars_exp(bexp)
    |> find_free_vars_body(then)
  end

  defp find_free_vars_if(map, [bexp, [do: thenbranch, else: elsebranch]]) do
    map
    |> find_free_vars_exp(bexp)
    |> find_free_vars_body(thenbranch)
    |> find_free_vars_body(elsebranch)
  end

  defp find_free_vars_exp(map, exp) do
    case exp do
      ## array index
      {{:., _i1, [Access, :get]}, _i2, [{array, _ia, _}, index]} ->
        {bound, free} = map

        if MapSet.member?(bound, array) do
          map
          |> find_free_vars_exp(index)
        else
          {bound, MapSet.put(free, array)}
          |> find_free_vars_exp(index)
        end

      # cuda constant
      {{:., _i1, [{_struct, _i2, nil}, _field]}, _i3, []} ->
        map

      # cuda constant
      {{:., _i1, [{:__aliases__, _i2, [_struct]}, _field]}, _i3, []} ->
        map

      {op, _info, args} when op in [:+, :-, :/, :*] ->
        # IO.inspect "Aqui"
        Enum.reduce(args, map, fn x, acc -> find_free_vars_exp(acc, x) end)

      {op, _info, args} when op in [:<=, :<, :>, :>=, :&&, :||, :!, :!=, :==] ->
        Enum.reduce(args, map, fn x, acc -> find_free_vars_exp(acc, x) end)

      {var, _info, nil} when is_atom(var) ->
        {bound, free} = map

        if MapSet.member?(bound, var) do
          map
        else
          {bound, MapSet.put(free, var)}
        end

      {_fun, _info, args} ->
        Enum.reduce(args, map, fn x, acc -> find_free_vars_exp(acc, x) end)

      # IO.inspect "Aqui2"
      # IO.inspect args
      # raise "function: #{inspect fun}"
      # {args,funs} = map
      # if MapSet.member?(args,fun) do
      #  map
      # else
      #  {args,MapSet.put(funs,fun)}
      # end
      float when is_float(float) ->
        map

      int when is_integer(int) ->
        map

      string when is_binary(string) ->
        map
    end
  end

  ####################################################
  ############### adds extra parameteres when calling a closure
  #### Takes a map (closure name -> extra para) and the ast,  and returns a new ast
  ########################
  def add_extra_closure_args(map, {:defk, i1, [header, [body]]}) do
    nbody = add_extra_closure_args__body(map, body)
    {:defk, i1, [header, [nbody]]}
  end

  def add_extra_closure_args__body(map, body) do
    case body do
      {:__block__, _, _code} ->
        add_extra_closure_args__block(map, body)

      {:do, {:__block__, pos, code}} ->
        {:do, add_extra_closure_args__block(map, {:__block__, pos, code})}

      {:do, exp} ->
        {:do, add_extra_closure_args__command(map, exp)}

      {_, _, _} ->
        add_extra_closure_args__command(map, body)
    end
  end

  defp add_extra_closure_args__block(map, {:__block__, info, code}) do
    {:__block__, info, Enum.map(code, fn com -> add_extra_closure_args__command(map, com) end)}
  end

  defp add_extra_closure_args__command(map, code) do
    case code do
      {:for, i, [param, [body]]} ->
        {:for, i, [param, [add_extra_closure_args__body(map, body)]]}

      {:do_while, i, [[doblock]]} ->
        {:do_while, i, [[add_extra_closure_args__body(map, doblock)]]}

      {:do_while_test, i, [exp]} ->
        {:do_while_test, i, [add_extra_closure_args__exp(map, exp)]}

      {:while, i, [bexp, [body]]} ->
        {:while, i,
         [add_extra_closure_args__exp(map, bexp), [add_extra_closure_args__body(map, body)]]}

      # CRIAÇÃO DE NOVOS VETORES
      {{:., i1, [Access, :get]}, i2, [arg1, arg2]} ->
        {{:., i1, [Access, :get]}, i2,
         [add_extra_closure_args__exp(map, arg1), add_extra_closure_args__exp(map, arg2)]}

      {:__shared__, i1, [{{:., i2, [Access, :get]}, i3, [arg1, arg2]}]} ->
        {:__shared__, i1,
         [
           {{:., i2, [Access, :get]}, i3,
            [add_extra_closure_args__exp(map, arg1), add_extra_closure_args__exp(map, arg2)]}
         ]}

      # assignment
      {:=, i1, [{{:., i2, [Access, :get]}, i3, [{array, a1, a2}, acc_exp]}, exp]} ->
        {:=, i1,
         [
           {{:., i2, [Access, :get]}, i3,
            [{array, a1, a2}, add_extra_closure_args__exp(map, acc_exp)]},
           add_extra_closure_args__exp(map, exp)
         ]}

      {:=, i, [var, exp]} ->
        {:=, i, [var, add_extra_closure_args__exp(map, exp)]}

      {:if, i, if_com} ->
        {:if, i, add_extra_closure_args__if(map, if_com)}

      {:var, i1, [{var, i2, [{:=, i3, [{type, ii, nil}, exp]}]}]} ->
        {:var, i1,
         [{var, i2, [{:=, i3, [{type, ii, nil}, add_extra_closure_args__exp(map, exp)]}]}]}

      {:var, i1, [{var, i2, [{:=, i3, [type, exp]}]}]} ->
        {:var, i1, [{var, i2, [{:=, i3, [type, add_extra_closure_args__exp(map, exp)]}]}]}

      {:var, i1, [{var, i2, [{type, i3, t}]}]} ->
        {:var, i1, [{var, i2, [{type, i3, t}]}]}

      {:var, i1, [{var, i2, [type]}]} ->
        {:var, i1, [{var, i2, [type]}]}

      {:type, i1, [{var, i2, [{type, i3, t}]}]} ->
        {:type, i1, [{var, i2, [{type, i3, t}]}]}

      {:type, i1, [{var, i2, [type]}]} ->
        {:type, i1, [{var, i2, [type]}]}

      {:return, i, [arg]} ->
        {:return, i, [add_extra_closure_args__exp(map, arg)]}

      {fun, info, args} when is_list(args) ->
        case map[fun] do
          nil ->
            {fun, info, Enum.map(args, fn exp -> add_extra_closure_args__exp(map, exp) end)}

          extra_args ->
            new_args = Enum.map(extra_args, fn p -> {p, [], nil} end)

            {fun, info,
             Enum.map(args, fn exp -> add_extra_closure_args__exp(map, exp) end) ++ new_args}
        end

      number when is_integer(number) or is_float(number) ->
        raise "Error: number is a command"

      {str, i1, a} ->
        {str, i1, a}
    end
  end

  defp add_extra_closure_args__if(map, [bexp, [do: then]]) do
    [add_extra_closure_args__exp(map, bexp), [do: add_extra_closure_args__body(map, then)]]
  end

  defp add_extra_closure_args__if(map, [bexp, [do: thenbranch, else: elsebranch]]) do
    [
      add_extra_closure_args__exp(map, bexp),
      [
        do: add_extra_closure_args__body(map, thenbranch),
        else: add_extra_closure_args__body(map, elsebranch)
      ]
    ]
  end

  defp add_extra_closure_args__exp(map, exp) do
    case exp do
      {{:., i1, [Access, :get]}, i2, [arg1, arg2]} ->
        {{:., i1, [Access, :get]}, i2, [arg1, add_extra_closure_args__exp(map, arg2)]}

      {{:., i1, [{struct, i2, nil}, field]}, i3, []} ->
        {{:., i1, [{struct, i2, nil}, field]}, i3, []}

      {{:., i1, [{:__aliases__, i2, [struct]}, field]}, i3, []} ->
        {{:., i1, [{:__aliases__, i2, [struct]}, field]}, i3, []}

      {op, info, args} when op in [:+, :-, :/, :*] ->
        {op, info, Enum.map(args, fn e -> add_extra_closure_args__exp(map, e) end)}

      {op, info, args} when op in [:<=, :<, :>, :>=, :&&, :||, :!, :!=, :==] ->
        {op, info, Enum.map(args, fn e -> add_extra_closure_args__exp(map, e) end)}

      {var, info, nil} when is_atom(var) ->
        {var, info, nil}

      {fun, info, args} ->
        case map[fun] do
          nil ->
            {fun, info, Enum.map(args, fn exp -> add_extra_closure_args__exp(map, exp) end)}

          extra_args ->
            new_args = Enum.map(extra_args, fn p -> {p, [], nil} end)

            {fun, info,
             Enum.map(args, fn exp -> add_extra_closure_args__exp(map, exp) end) ++ new_args}
        end

      float when is_float(float) ->
        float

      int when is_integer(int) ->
        int

      string when is_binary(string) ->
        string
    end
  end

  ##################################
  ############# END closure elimination
  ###################################

  @doc """
  Generates a mapping of formal parameters to their respective types, including the return type.
  ## Parameters
    - `code`: The abstract syntax tree (AST) of the function/kernel.
    - `type`: A tuple containing the return type and a list of types for the parameters.
  ## Returns
    - A map where keys are formal parameter names and values are their corresponding types. The return type is stored with the key `:return`.
  """
  def gen_delta_from_type({:defd, _, [header, [_body]]}, {return_type, types}) do
    {_, _, formal_para} = header

    delta =
      formal_para
      |> preprocess_formal_parameters()
      |> get_param_vars()
      |> Enum.zip(types)
      |> Map.new()

    Map.put(delta, :return, return_type)
  end

  def gen_delta_from_type({:fn, _, [{:->, _, [para, _body]}]}, {return_type, types}) do
    delta =
      para
      |> preprocess_formal_parameters()
      |> get_param_vars()
      |> Enum.zip(types)
      |> Map.new()

    Map.put(delta, :return, return_type)
  end

  @doc """
  Infers the types of variables in the function's AST based on the provided delta mapping.

  ## Parameters
    - `code`: The abstract syntax tree (AST) of the function.
    - `delta`: A map where keys are variable names and values are their corresponding types.

  ## Returns
    - A tuple containing:
      - `:ok` if the type inference was successful without any type errors, or `:error` if there were type errors.
      - A map where keys are variable names and values are their inferred types.
      - An optional reason for the error if the inference failed.
  """
  def infer_types({:defk, _, [_header, [body]]}, delta, kernel_name) do
    PolyHok.TypeInference.type_check(delta, body, kernel_name)
  end

  def infer_types({:defd, _, [_header, [body]]}, delta, fun_name) do
    PolyHok.TypeInference.type_check(delta, body, fun_name)
  end

  def infer_types({:fn, _, [{:->, _, [_para, body]}]}, delta, fun_name) do
    PolyHok.TypeInference.type_check(delta, body, fun_name)
  end

  @doc """
  Retrieves the AST of all non-parameter functions called within a kernel or device function.

  ## Parameters
    - `fun_graph`: A list of function names (atoms) that are called within the kernel or device function.

  ## Returns
    - A list of tuples {function_name, ast, functions_called} where:
      - `function_name` is the name of the function.
      - `ast` is the abstract syntax tree of the function.
      - `functions_called` is a list of functions that are called within this function.
  """
  def get_non_parameters_func_asts([]), do: []

  def get_non_parameters_func_asts(fun_graph) do
    fun_graph
    # discard special functions
    |> Enum.filter(fn f -> not PolyHok.TypeInference.is_special_function?(f) end)
    # Load ast and filter function graph
    |> Enum.map(fn f ->
      # Load function ast from module server
      {ast, funs} =
        case PolyHok.load_ast(f) do
          nil ->
            raise "Error: function '#{f}' not found. Function may not been declared or doesn't exist."

          {ast, funs} ->
            {ast, funs}
        end

      # Remove special functions from the list of functions called inside the function
      funs =
        Enum.filter(funs, fn fun -> not PolyHok.TypeInference.is_special_function?(fun) end)

      # Return function name, its ast and function graph as a tuple
      {f, ast, funs}
    end)
    # Load functions called by functions in the list as well
    |> Enum.flat_map(fn {f, ast, funs} ->
      [{f, ast, funs} | get_non_parameters_func_asts(funs)]
    end)
  end

  @doc """
  Sorts the functions used within the kernel by their call graph, so that if a function A calls a function B, then B will be before A in the list.

  Uses the CallGraphSorter module to perform a topological sort of the functions based on their call graph.

  ## Parameters
    - A list of tuples {function_name, ast, functions_called} where:
      - `function_name` is the name of the function.
      - `ast` is the abstract syntax tree of the function.
      - `functions_called` is a list of functions that are called within this function.

  ## Returns
    - A list of tuples {function_name, ast} sorted by their call graph.
  """
  def sort_functions_by_call_graph([]), do: []

  def sort_functions_by_call_graph(funs_graph_asts) do
    PolyHok.CallGraphSorter.sort(funs_graph_asts)
  end

  @doc """
  Finds the types of the actual parameters and creates a mapping of formal parameters to these inferred types.
  """
  def gen_kernel_initial_delta({:defk, _, [header, [_body]]}, actual_param) do
    {_, _, formal_para} = header

    inferred_types = infer_types_actual_parameters(actual_param)

    formal_para
    |> preprocess_formal_parameters()
    |> Enum.zip(inferred_types)
    |> Map.new()
  end

  @doc """
  Infers the types of actual parameters passed to a kernel or function.

  ## Parameters

    - `actual_param`: A list of actual parameters passed to the kernel or function.

  ## Returns
    - A list of inferred types corresponding to the actual parameters. These types are represented as atoms.

    The types allowed are:
      - `:tfloat` for 32-bit floating-point numbers.
      - `:tdouble` for 64-bit floating-point numbers.
      - `:tint` for 32-bit integers.
      - `:float` for literal floating-point numbers.
      - `:int` for literal integers.
      - `:none` for function types (like anonymous functions or function references).
  """
  def infer_types_actual_parameters([]) do
    []
  end

  def infer_types_actual_parameters([h | t]) do
    case h do
      # GNx
      {:nx, type, _shape, _name, _ref} ->
        case type do
          tp when tp in [:f32, {:f, 32}] -> [:tfloat | infer_types_actual_parameters(t)]
          tp when tp in [:f64, {:f, 64}] -> [:tdouble | infer_types_actual_parameters(t)]
          tp when tp in [:s32, {:s, 32}] -> [:tint | infer_types_actual_parameters(t)]
        end

      {:anon, _name, _fun_inn_funs} ->
        [:none | infer_types_actual_parameters(t)]

      float when is_float(float) ->
        [:float | infer_types_actual_parameters(t)]

      int when is_integer(int) ->
        [:int | infer_types_actual_parameters(t)]

      func when is_function(func) ->
        [:none | infer_types_actual_parameters(t)]
    end
  end

  @doc """
  The gen_dev_fun_initial_delta is just a trick =D
  Since the function signature of a device function doesn't include any hint about its parameters types,
  we set all of them to :none, so the TypeInference module will try to figure out the types based on the body of the
  device function only.
  """
  def gen_dev_fun_initial_delta({:defd, _, [header, [_body]]}) do
    {_, _, formal_para} = header

    preprocess_formal_parameters(formal_para)
    |> get_param_vars()
    |> Enum.map(fn p -> {p, :none} end)
    |> Map.new()
  end

  # Returns a list of atoms representing the names of the formal parameters of a device function/kernel.
  defp get_parameter_names_list({_defd_defk, _, [header, [_body]]}) do
    {_, _, formal_para} = header

    formal_para |> preprocess_formal_parameters() |> get_param_vars()
  end

  @doc """
  Infers the types of the provided device functions based on their ASTs. Each inferred function is added to a delta map with its name
  as the key and its type signature as the value and this delta is used to infer the types of the next functions in the list,
  so the order of the functions in the list is important and is based on the call graph of the functions
  (a function that calls another function should be after it in the list).

  ## Parameters
    - `funs_graph_asts`: A list of tuples {function_name, ast}
  ## Returns
    - A delta map where keys are function names and values are their type signatures in the format {return_type, [param_types]}.
  """
  def infer_device_functions_signature([]), do: Map.new()

  def infer_device_functions_signature(funs_graph_asts) do
    # Remove functions that were not found (ast == nil)
    funs_graph_asts = funs_graph_asts |> Enum.filter(fn {_f, ast} -> ast != nil end)

    Enum.reduce(funs_graph_asts, Map.new(), fn {f, ast}, delta ->
      delta_fun = gen_dev_fun_initial_delta(ast)

      # Add the previous inferred types of the delta map to delta_fun,
      # so when we infer the types of the current function, it can use the types of the previous functions
      # in the list that it calls.
      delta_fun = Map.merge(delta_fun, delta)

      case infer_types(ast, delta_fun, f) do
        {:ok, types} ->
          # Get the current function type signature in the format {return_type, [param_types]}
          fun_sig =
            {Map.get(types, :return),
             get_parameter_names_list(ast) |> Enum.map(fn p -> Map.get(types, p) end)}

          # Add it to the delta map with the function name as key
          Map.put(delta, f, fun_sig)

        {:error, _types, reason} ->
          raise "Type inference failed for device function #{f}: #{reason}"
      end
    end)
  end

  @doc """
  Extracts the function name from an anonymous function or a function reference.

  ## Parameters

    - `fun`: The function, which can be either an anonymous function or a device function reference.

  ## Returns
    - The atom representing the function name.
  """
  def get_function_name({:anon, lambda_name, _fun_inn_funs}) do
    lambda_name
  end

  def get_function_name(fun) do
    {_module, f_name} =
      case Macro.escape(fun) do
        {:&, [], [{:/, [], [{{:., [], [module, f_name]}, [no_parens: true], []}, _nargs]}]} ->
          {module, f_name}

        _ ->
          raise "Argument should be a function: #{inspect(Macro.escape(fun))}"
      end

    f_name
  end

  @doc """
  Extracts the kernel function name from a given kernel reference.

  ## Parameters

    - `kernel`: A function reference, like `&Module.function/arity`.

  ## Returns

    - The atom representing the kernel function name.

  ## Raises

    - Raises an exception if the provided kernel is not a valid function reference.
  """
  def get_kernel_name(kernel) do
    case Macro.escape(kernel) do
      {:&, [], [{:/, [], [{{:., [], [_module, kernelname]}, [no_parens: true], []}, _nargs]}]} ->
        kernelname

      _ ->
        IO.inspect(kernel, label: "Invalid kernel")
        raise "PolyHok: invalid kernel"
    end
  end

  def is_anon(func) do
    case func do
      {:anon, _name, _fun_inn_funs} -> true
      _ -> false
    end
  end

  def is_function_para(func) do
    case func do
      {:anon, _name, _fun_inn_funs} -> true
      func when is_function(func) -> true
      _h -> false
    end
  end

  @doc """
  Returns a map of formal parameters (that are functions) mapped to their actual names in the target code.
  """
  def get_function_parameters({:defk, _, [header, [_body]]}, actual_para) do
    {_, _, formal_para} = header

    formal_para
    |> preprocess_formal_parameters()
    |> get_param_vars()
    |> Enum.zip(actual_para)
    |> Enum.filter(fn {_n, p} -> is_function_para(p) end)
    |> Enum.reduce(Map.new(), fn {n, p}, map -> Map.put(map, n, get_function_name(p)) end)
  end

  @doc """
  Returns a list of tuples {actual_function_name, type} of all formal parameters that are functions.

  If the actual parameter is an anonymous function, it returns {:anon, name, _fun_inn_funs, type}.
  """
  def get_function_parameters_and_their_types({:defk, _, [header, [_body]]}, actual_para, delta) do
    {_, _, formal_para} = header

    formal_para
    |> preprocess_formal_parameters()
    |> get_param_vars()
    |> Enum.zip(actual_para)
    |> Enum.filter(fn {_f_p, a_p} -> is_function_para(a_p) end)
    |> Enum.map(fn {f_p, a_p} ->
      case a_p do
        {:anon, name, fun_inn_funs} -> {:anon, name, fun_inn_funs, delta[f_p]}
        _ -> {get_function_name(a_p), delta[f_p]}
      end
    end)
  end

  @doc """
  Retrieves the code for the includes stored in the module server.

  # Returns
    - A string containing the concatenated include code.
  """
  def get_includes() do
    send(:module_server, {:get_include, self()})

    inc =
      receive do
        {:include, inc} -> inc
        h -> raise "unknown message for function type server #{inspect(h)}"
      end

    case inc do
      nil -> ""
      list -> Enum.reduce(list, "", fn x, y -> y <> x end)
    end
  end

  @doc """
  Returns a list of types of all formal parameters of a kernel, excluding function types.

  ## Parameters

    - `kernel_ast`: The abstract syntax tree (AST) of the kernel definition.
    - `delta`: A map where keys are variable names and values are their corresponding types.

  ## Returns
    - A list of charlists representing the types of the formal parameters.
  """
  def get_types_para({:defk, _, [header, [_body]]}, delta) do
    {_, _, formal_para} = header

    formal_para
    |> preprocess_formal_parameters()
    |> get_param_vars()
    |> Enum.map(fn p -> delta[p] end)
    |> Enum.filter(fn p ->
      case p do
        # Ignoring function types
        {_, _} -> false
        _ -> true
      end
    end)
    |> Enum.map(fn x -> Kernel.to_charlist(to_string(x)) end)
  end

  @doc """
  Processes a module and populates the module_server with information about functions (their ast, and call graph).
  It spawns a module server if it is not already running, which contains two maps:

  - A map of function names to their types.
  - A map of function names to their ASTs.

  ## Parameters

    - `module_name`: The name of the module to process.
    - `body`: The body or content associated with the module.
  """
  def process_module(module_name, body) do
    # initiate server that collects types and asts
    if Process.whereis(:module_server) == nil do
      pid = spawn_link(fn -> module_server(%{}, %{}, %{}) end)
      Process.register(pid, :module_server)
    end

    # If the module body is a block, process its definitions, otherwise process the body directly.
    # Usually, if the body is not a block, it will be a single definition of function or kernel.
    _defs =
      case body do
        {:__block__, [], definitions} -> process_definitions(module_name, definitions, [])
        _ -> process_definitions(module_name, [body], [])
      end
  end

  @doc """
  This server constructs three maps:
  - Function names to types.
  - Function names to {AST, functions_called}.
  - Map of compiled kernels.
    - Keys are {kernel_name, kernel_types_and_funs} tuples
    - Values are the compiled kernel code as an Erlang resource

  Types are used to type check at runtime a kernel call, while ASTs are used to recompile a kernel at runtime,
  substituting the names of the formal parameters of a function for the actual parameters.
  """
  def module_server(types_map, ast_map, kernels_map) do
    receive do
      {:add_ast, fun, ast, funs} ->
        module_server(types_map, Map.put(ast_map, fun, {ast, funs}), kernels_map)

      {:get_ast, f_name, pid} ->
        send(pid, {:ast, ast_map[f_name]})
        module_server(types_map, ast_map, kernels_map)

      {:add_type, fun, type} ->
        module_server(Map.put(types_map, fun, type), ast_map, kernels_map)

      {:get_map, pid} ->
        send(pid, {:map, {types_map, ast_map}})
        module_server(types_map, ast_map, kernels_map)

      {:get_include, pid} ->
        send(pid, {:include, ast_map[:include]})
        module_server(types_map, ast_map, kernels_map)

      {:add_include, inc} ->
        case ast_map[:include] do
          nil -> module_server(types_map, Map.put(ast_map, :include, [inc]), kernels_map)
          l -> module_server(types_map, Map.put(ast_map, :include, [inc | l]), kernels_map)
        end

      {:get_kernel, kernel_key, pid} ->
        send(pid, {:kernel, kernels_map[kernel_key]})
        module_server(types_map, ast_map, kernels_map)

      {:add_kernel, kernel_key, kernel} ->
        module_server(types_map, ast_map, Map.put(kernels_map, kernel_key, kernel))

      {:kill} ->
        :ok
    end
  end

  # Processes a list of definitions (kernels, device functions, include directives) and registers them
  # in the module server.
  #
  ## Parameters
  #
  #  - `module_name`: The name of the module being processed.
  #  - `definitions`: The ast of the module to process its definitions.
  #  - `l`: An accumulator list (not used in this implementation).
  #
  ## Returns
  #  - `:ok` when all definitions have been processed.
  defp process_definitions(_module_name, [], _l), do: :ok

  defp process_definitions(module_name, [h | t], l) do
    case h do
      {:defk, _, [header, [_body]]} ->
        # Get function name from header
        {fname, _, _para} = header
        # Get list of functions called inside the kernel
        funs = find_functions(h)
        # Register the function in the module server
        register_function(module_name, fname, h, funs)
        # Go to next definition
        process_definitions(module_name, t, [
          {module_name, fname, h, funs} | t
        ])

      {:defd, ii, [header, [body]]} ->
        # Get function name from header
        {fname, _, _para} = header

        # IO.puts("Processing device function: #{fname}")
        # IO.inspect(body, label: "Original body")

        # Travels the function body and adds a return statement if the function returns an expression
        body = PolyHok.TypeInference.add_return(body)

        # IO.inspect(body, label: "body with return added")

        # Get list of functions called inside the device function
        funs = find_functions({:defd, ii, [header, [body]]})
        # Register the function in the module server
        register_function(module_name, fname, {:defd, ii, [header, [body]]}, funs)
        # Go to next definition
        process_definitions(module_name, t, [
          {module_name, fname, {:defd, ii, [header, [body]]}, funs} | l
        ])

      {:include, _, [{_, _, [name]}]} ->
        # The include directive will read a target code file with the name given in the include directive
        # and add it to the module server so that it can be added in the kernel or device function later.
        code = File.read!("ph_includes/#{name}.c")
        send(:module_server, {:add_include, code})
        process_definitions(module_name, t, l)

      _ ->
        # If it is not a device function/kernel definition nor an include directive,
        # ignore and continue processing the rest of the definitions.
        process_definitions(module_name, t, l)
    end
  end

  @doc """
  Registers a function in the module server.

  ## Parameters

    - `_module_name`: The name of the module (not used in this function).
    - `fun_name`: The name of the function to register.
    - `ast`: The abstract syntax tree (AST) of the function.
    - `funs`: A list of functions called within the function being registered.
  """
  def register_function(_module_name, fun_name, ast, funs) do
    send(:module_server, {:add_ast, fun_name, ast, funs})
  end

  @doc """
  Finds all function calls within a kernel or device function definition.

  ## Parameters
    - `ast`: The abstract syntax tree (AST) of the kernel or device function definition.

  ## Returns
    - A list of function names (atoms) that are called within the kernel or device function.
  """
  def find_functions({:defk, _i1, [header, [body]]}) do
    {_fname, _, para} = header

    param_vars =
      para
      |> preprocess_formal_parameters()
      |> get_param_vars()
      |> MapSet.new()

    {_args, funs} = find_function_calls_body({param_vars, MapSet.new()}, body)

    MapSet.to_list(funs)
  end

  def find_functions({:defd, _i1, [header, [body]]}) do
    # IO.inspect "aqui inicio"
    {_fname, _, para} = header

    param_vars =
      para
      |> preprocess_formal_parameters()
      |> get_param_vars()
      |> MapSet.new()

    # IO.inspect "body #{inspect body}"
    {_args, funs} = find_function_calls_body({param_vars, MapSet.new()}, body)

    MapSet.to_list(funs)
  end

  def find_functions({:fn, _aa, [{:->, _bb, [para, body]}]}) do
    param_vars =
      para
      |> preprocess_formal_parameters()
      |> get_param_vars()
      |> MapSet.new()

    {_args, funs} = find_function_calls_body({param_vars, MapSet.new()}, body)

    MapSet.to_list(funs)
  end

  @doc """
  Traverses the body of a kernel or device function to find function calls.
  ## Parameters
    - `map`: A tuple containing a set of parameter names and a set of function names found.
    - `body`: The body of the kernel or device function.

  ## Returns
    - An updated tuple with the set of parameter names and the set of function names found.
  """
  def find_function_calls_body(map, body) do
    case body do
      {:__block__, _, _code} ->
        find_function_calls_block(map, body)

      {:do, {:__block__, pos, code}} ->
        find_function_calls_block(map, {:__block__, pos, code})

      {:do, exp} ->
        # IO.inspect "here #{inspect exp}"
        find_function_calls_command(map, exp)

      {_, _, _} ->
        find_function_calls_command(map, body)
    end
  end

  # Uses reduce to iterate through each command in the block
  # and applies find_function_calls_command to each one.
  defp find_function_calls_block(map, {:__block__, _info, code}) do
    Enum.reduce(code, map, fn x, acc -> find_function_calls_command(acc, x) end)
  end

  # Pattern matches every possible command structure to find function calls.
  # It handles various constructs like loops, conditionals, assignments, and function calls.
  # It also checks for function calls in conditional expressions and assignments.
  # When it finds a function call, it adds it to the set of functions in the map only if
  # the function is not in the parameters list of the kernel or device function.
  defp find_function_calls_command(map, code) do
    # IO.inspect(code, label: "find_function_calls_command")
    case code do
      {:for, _i, [_param, [body]]} ->
        find_function_calls_body(map, body)

      {:do_while, _i, [[doblock]]} ->
        find_function_calls_body(map, doblock)

      {:do_while_test, _i, [exp]} ->
        find_function_calls_exp(map, exp)

      {:while, _i, [bexp, [body]]} ->
        map = find_function_calls_exp(map, bexp)
        find_function_calls_body(map, body)

      # CRIAÇÃO DE NOVOS VETORES
      {{:., _i1, [Access, :get]}, _i2, [arg1, arg2]} ->
        map = find_function_calls_exp(map, arg1)
        find_function_calls_exp(map, arg2)

      {shared_atom, _i1, [{{:., _i2, [Access, :get]}, _i3, [arg1, arg2]}]}
      when shared_atom in [:__shared__, :__local, :__atomic_local] ->
        map = find_function_calls_exp(map, arg1)
        find_function_calls_exp(map, arg2)

      # assignment
      {:=, _i1, [{{:., _i2, [Access, :get]}, _i3, [{_array, _a1, _a2}, acc_exp]}, exp]} ->
        map = find_function_calls_exp(map, acc_exp)
        find_function_calls_exp(map, exp)

      {:=, _i, [_var, exp]} ->
        find_function_calls_exp(map, exp)

      {:if, _i, if_com} ->
        find_function_calls_if(map, if_com)

      {:var, _i1, [{_var, _i2, [{:=, _i3, [{_type, _ii, nil}, exp]}]}]} ->
        find_function_calls_exp(map, exp)

      {:var, _i1, [{_var, _i2, [{:=, _i3, [_type, exp]}]}]} ->
        find_function_calls_exp(map, exp)

      {:var, _i1, [{_var, _i2, [{_type, _i3, _t}]}]} ->
        map

      {:var, _i1, [{_var, _i2, [_type]}]} ->
        map

      {:type, _i1, [{_var, _i2, [{_type, _i3, _t}]}]} ->
        map

      {:type, _i1, [{_var, _i2, [_type]}]} ->
        map

      {:return, _i, [arg]} ->
        #     IO.inspect "Aqui3"
        find_function_calls_exp(map, arg)

      {:return, _i, nil} ->
        map

      {fun, _info, args} when is_list(args) ->
        #    IO.inspect "Aqui3 #{length args} #{inspect fun}"
        {args, funs} = map

        if MapSet.member?(args, fun) do
          map
        else
          {args, MapSet.put(funs, fun)}
        end

      number when is_integer(number) or is_float(number) ->
        raise "Error: #{inspect(number)} is a command"

      {str, i1, a} ->
        {str, i1, a}
    end
  end

  defp find_function_calls_if(map, [bexp, [do: then]]) do
    map = find_function_calls_exp(map, bexp)
    find_function_calls_body(map, then)
  end

  defp find_function_calls_if(map, [bexp, [do: thenbranch, else: elsebranch]]) do
    map = find_function_calls_exp(map, bexp)
    map = find_function_calls_body(map, thenbranch)
    find_function_calls_body(map, elsebranch)
  end

  # This function recursively traverses the expression tree to find function calls.
  defp find_function_calls_exp(map, exp) do
    case exp do
      {{:., _i1, [Access, :get]}, _i2, [_arg1, arg2]} ->
        find_function_calls_exp(map, arg2)

      {{:., _i1, [{_struct, _i2, nil}, _field]}, _i3, []} ->
        map

      {{:., _i1, [{:__aliases__, _i2, [_struct]}, _field]}, _i3, []} ->
        map

      {op, _info, args} when op in [:+, :-, :/, :*] ->
        # IO.inspect "Aqui"
        Enum.reduce(args, map, fn x, acc -> find_function_calls_exp(acc, x) end)

      {op, _info, args} when op in [:>>>, :<<<, :~>>, :&&&, :|||, :+++] ->
        Enum.reduce(args, map, fn x, acc -> find_function_calls_exp(acc, x) end)

      {op, _info, args} when op in [:<=, :<, :>, :>=, :&&, :||, :!, :!=, :==] ->
        Enum.reduce(args, map, fn x, acc -> find_function_calls_exp(acc, x) end)

      {var, _info, nil} when is_atom(var) ->
        map

      {fun, _info, _args} ->
        # IO.inspect "Aqui2"
        {args, funs} = map

        if MapSet.member?(args, fun) do
          map
        else
          {args, MapSet.put(funs, fun)}
        end

      float when is_float(float) ->
        map

      int when is_integer(int) ->
        map

      string when is_binary(string) ->
        map
    end
  end
end
