defmodule CudaBackend do
  @moduledoc """
  Implements the `PolyHok.BackendBehaviour` for generating CUDA code from the provided  ASTs.
  """
  @behaviour PolyHok.BackendBehaviour
  @on_load :load_nifs

  def load_nifs do
    :erlang.load_nif("./priv/gpu_nifs", 0)
  end

  @doc """
  Generates a new Elixir module AST with a custom `__using__/1` macro and transformed function definitions.

  ## Parameters

    - `header`: The module header AST, typically an `{:__aliases__, _, [module_name]}` tuple representing the module name.
    - `body`: The body of the module, which can be a single definition or a block of definitions.

  ## Returns

    - An Elixir quoted expression (`quote`) that defines a new module with:
      - A `__using__/1` macro that invokes `JIT.process_module/2` with the module name and original body.
      - The transformed function definitions generated by `gen_new_definitions/1`.
  """
  @impl PolyHok.BackendBehaviour
  def gen_new_module(header, body) do
    new_body =
      case body do
        {:__block__, [], definitions} -> gen_new_definitions(definitions)
        _ -> gen_new_definitions([body])
      end

    {:__aliases__, _, [module_name]} = header

    # IO.inspect body

    using =
      quote do
        defmacro __using__(_opts) do
          JIT.process_module(unquote(module_name), unquote(Macro.escape(body)))
        end
      end

    # IO.inspect using
    # IO.inspect new_body
    # using = {:defmacro, [line: 16, column: 3],
    #  [
    #  {:__using__, [line: 16, column: 12],
    #  [{:_opts, [line: 16, column: 22], nil}]},
    #  [
    #   do: {{:., [line: 17, column: 10],
    #     [{:__aliases__, [line: 17, column: 8], [:IO]}, :puts]},
    #    [line: 17, column: 11], ["You are USIng!"]}
    #  ]
    # ]}
    new_module =
      quote do
        defmodule unquote(header) do
          unquote([using | new_body])
        end
      end

    new_module
  end

  defp gen_new_definitions([]), do: []

  defp gen_new_definitions([{:include, _, _para} | t]) do
    gen_new_definitions(t)
  end

  defp gen_new_definitions([{:defd, _, [header, _code]} | t]) do
    {fname, comp_info, para} = header

    para =
      para
      |> Enum.map(fn {p, b, c} -> {String.to_atom("_" <> to_string(p)), b, c} end)

    new_code =
      quote do:
              def(unquote({fname, comp_info, para}),
                do: raise("A hok function can only be called by kernels!")
              )

    [new_code | gen_new_definitions(t)]
  end

  defp gen_new_definitions([{:defk, _, [header, _code]} | t]) do
    {fname, comp_info, para} = header

    para =
      para
      |> Enum.map(fn {p, b, c} -> {String.to_atom("_" <> to_string(p)), b, c} end)

    new_code =
      quote do:
              def(unquote({fname, comp_info, para}),
                do: raise("A kernel can only be executed with spawn!")
              )

    [new_code | gen_new_definitions(t)]
  end

  defp gen_new_definitions([h | t]) do
    # IO.inspect h
    [h | gen_new_definitions(t)]
  end

  @impl PolyHok.BackendBehaviour
  def gen_para(p, :tint) do
    "int *#{p}"
  end

  @impl PolyHok.BackendBehaviour
  def gen_para(p, :tfloat) do
    "float *#{p}"
  end

  @impl PolyHok.BackendBehaviour
  def gen_para(p, :tdouble) do
    "double *#{p}"
  end

  @impl PolyHok.BackendBehaviour
  def gen_para(p, :int) do
    "int #{p}"
  end

  @impl PolyHok.BackendBehaviour
  def gen_para(p, :float) do
    "float #{p}"
  end

  @impl PolyHok.BackendBehaviour
  def gen_para(p, :double) do
    "double #{p}"
  end

  @impl PolyHok.BackendBehaviour
  def gen_para(_p, {_ret, _type}) do
    nil
  end

  # def gen_kernel(name, para, body) do
  #   "__global__\nvoid #{name}(#{para})\n{\n#{body}\n}"
  # end

  @impl PolyHok.BackendBehaviour
  def declare_kernel(name, param_list_str, body) do
    "__global__\nvoid #{name}(#{param_list_str})\n{\n#{body}\n}"
  end

  # def gen_function(name, para, body, type) do
  #   "__device__\n#{type} #{name}(#{para})\n{\n#{body}\n}"
  # end

  @impl PolyHok.BackendBehaviour
  def declare_function(name, param_list_str, body, return_type) do
    "__device__\n#{return_type} #{name}(#{param_list_str})\n{\n#{body}\n}"
  end

  # def gen_cuda_jit(body, types, param_vars, module, subs) do
  #   # IO.puts "##########################gen cuda"
  #   # IO.inspect types
  #   #  IO.puts "############end gen cuda"
  #   # raise "hell"
  #   # IO.puts "gen_cuda"
  #   # IO.inspect param_vars
  #   pid = spawn_link(fn -> types_server(param_vars, types, module, subs) end)
  #   Process.register(pid, :types_server)
  #   code = gen_body(body)
  #   send(pid, {:kill})
  #   Process.unregister(:types_server)
  #   code
  # end

  @impl PolyHok.BackendBehaviour
  def gen_code(body, types, param_vars, module_name, subs) do
    pid = spawn_link(fn -> types_server(param_vars, types, module_name, subs) end)
    Process.register(pid, :types_server)
    code = gen_body(body)
    send(pid, {:kill})
    Process.unregister(:types_server)
    code
  end

  defp gen_body(body) do
    case body do
      {:__block__, _, _code} ->
        gen_block(body)

      {:do, {:__block__, pos, code}} ->
        gen_block({:__block__, pos, code})

      {:do, exp} ->
        gen_command(exp)

      {_, _, _} ->
        gen_command(body)
    end
  end

  defp gen_block({:__block__, _, code}) do
    code
    |> Enum.map(&gen_command/1)
    |> Enum.join("\n")
  end

  defp gen_header_for(header) do
    case header do
      {:in, _, [{var, _, nil}, {:range, _, [n]}]} ->
        "for( int #{var} = 0; #{var}<#{gen_exp(n)}; #{var}++)"

      {:in, _, [{var, _, nil}, {:range, _, [argr1, argr2]}]} ->
        "for( int #{var} = #{gen_exp(argr1)}; #{var}<#{gen_exp(argr2)}; #{var}++)"

      {:in, _, [{var, _, nil}, {:range, _, [argr1, argr2, step]}]} ->
        "for( int #{var} = #{gen_exp(argr1)}; #{var}<#{gen_exp(argr2)}; #{var}+=#{gen_exp(step)})"
    end
  end

  # Generates CUDA code for a given AST node command
  defp gen_command(code) do
    case code do
      {:for, _, [param, [body]]} ->
        header = gen_header_for(param)
        body = gen_body(body)
        header <> "{\n" <> body <> "\n}\n"

      {:=, _, [arg, exp]} ->
        a = gen_exp(arg)
        e = gen_exp(exp)

        case arg do
          # Accessing array index
          {{:., _, [Access, :get]}, _, [_, _]} ->
            "\t#{a} = #{e}\;"

          _ ->
            send(:types_server, {:check_var, a, self()})

            receive do
              {:is_typed} ->
                "\t#{a} = #{e}\;"

              {:type, type} ->
                "\t#{type} #{a} = #{e}\;"

              {:alredy_declared} ->
                "\t#{a} = #{e}\;"
            end
        end

      {:if, _, if_com} ->
        genIf(if_com)

      {:do_while, _, [[doblock]]} ->
        "do{\n" <> gen_body(doblock)

      {:do_while_test, _, [exp]} ->
        "\nwhile(" <> gen_exp(exp) <> ");"

      {:while, _, [bexp, [body]]} ->
        "while(" <> gen_exp(bexp) <> "){\n" <> gen_body(body) <> "\n}"

      # CRIAÇÃO DE NOVOS VETORES
      {{:., _, [Access, :get]}, _, [arg1, arg2]} ->
        name = gen_exp(arg1)
        index = gen_exp(arg2)
        "float #{name}[#{index}];"

      # Work-group shared memory declaration
      {:__shared__, _, [{{:., _, [Access, :get]}, _, [arg1, arg2]}]} ->
        name = gen_exp(arg1)
        index = gen_exp(arg2)
        send(:types_server, {:check_var, name, self()})

        atype =
          receive do
            {:type, type} ->
              case type do
                :tint -> :int
                :tfloat -> :float
                :tdouble -> :double
                u -> raise "Type #{u} given to array #{name}"
              end

            _ ->
              raise "Var #{name} already declared."
          end

        "__shared__ #{atype} #{name}[#{index}];"

      {:__syncthreads, _, _} ->
        "__syncthreads();"

      {:var, _, [{var, _, [{:=, _, [{type, _, nil}, exp]}]}]} ->
        # IO.puts "aqui"
        gexp = gen_exp(exp)
        "#{to_string(type)} #{to_string(var)} = #{gexp};"

      {:var, _, [{var, _, [{:=, _, [type, exp]}]}]} ->
        gexp = gen_exp(exp)
        "#{to_string(type)} #{to_string(var)} = #{gexp};"

      {:var, _, [{var, _, [{type, _, _}]}]} ->
        "#{to_string(type)} #{to_string(var)};"

      {:var, _, [{var, _, [type]}]} ->
        "#{to_string(type)} #{to_string(var)};"

      {:type, _, [{_, _, [{_, _, _}]}]} ->
        ""

      {:type, _, [{_, _, _}]} ->
        ""

      {:return, _, [arg]} ->
        "return (#{gen_exp(arg)});"

      {:return, _, nil} ->
        "return;"

      {fun, _, args} when is_list(args) ->
        nargs =
          args
          |> Enum.map(&gen_exp/1)
          |> Enum.join(", ")

        nfun = check_fun(fun)

        if nfun == nil do
          "#{fun}(#{nargs});"
        else
          "#{nfun}(#{nargs});"
        end

      {str, _, _} ->
        "#{to_string(str)};"

      number when is_integer(number) or is_float(number) ->
        to_string(number)
    end
  end

  # Gera uma expressão em C a partir de uma expressão PolyHok.
  defp gen_exp(exp) do
    case exp do
      # Acesso a um índice de um array
      {{:., _, [Access, :get]}, _, [arg1, arg2]} ->
        name = gen_exp(arg1)
        index = gen_exp(arg2)
        "#{name}[#{index}]"

      # Esse pattern vai ser acionado quando estivermos acessando estruturas especiais de indexação da GPU (ex: threadIdx.x, blockIdx.y, etc.). É só retornar os átomos como estão.
      {{:., _, [{struct, _, _}, field]}, _, []} ->
        "#{to_string(struct)}.#{to_string(field)}"

      # Mesma ideia aqui. Não sei dizer quando que esse __aliases__ vai ser acionado, mas é bom ter por aqui também.
      {{:., _, [{:__aliases__, _, [struct]}, field]}, _, []} ->
        "#{to_string(struct)}.#{to_string(field)}"

      {op, _, args} when op in [:+, :-, :/, :*, :<=, :<, :>, :>=, :&&, :||, :!, :!=, :==] ->
        case args do
          [a1] ->
            "(#{to_string(op)} #{gen_exp(a1)})"

          [a1, a2] ->
            "(#{gen_exp(a1)} #{to_string(op)} #{gen_exp(a2)})"
        end

      # Support for bitwise operators
      {op, _, args} when op in [:<<<, :>>>, :~>>, :&&&, :|||, :+++] ->
        str_op =
          case op do
            :<<< -> "<<"
            :>>> -> ">>"
            :~>> -> "%"
            :&&& -> "&"
            :||| -> "|"
            :+++ -> "^"
          end

        case args do
          [a1, a2] ->
            "(#{gen_exp(a1)} #{str_op} #{gen_exp(a2)})"
        end

      {var, _, nil} when is_atom(var) ->
        to_string(var)

      {fun, _, args} ->
        nargs =
          args
          |> Enum.map(&gen_exp/1)
          |> Enum.join(", ")

        nfun = check_fun(fun)

        if nfun == nil do
          "#{fun}(#{nargs})"
        else
          "#{nfun}(#{nargs})"
        end

      number when is_integer(number) or is_float(number) ->
        to_string(number)

      string when is_binary(string) ->
        "\"#{string}\""
    end
  end

  defp genIf([bexp, [do: then]]) do
    gen_then([bexp, [do: then]])
  end

  defp genIf([bexp, [do: thenbranch, else: elsebranch]]) do
    gen_then([bexp, [do: thenbranch]]) <>
      "else{\n" <>
      gen_body(elsebranch) <>
      "\n}\n"
  end

  defp gen_then([bexp, [do: then]]) do
    "if(#{gen_exp(bexp)})\n" <>
      "{\n" <>
      gen_body(then) <>
      "\n}\n"
  end

  defp types_server(used, types, module, subs) do
    receive do
      {:module, pid} ->
        send(pid, {:module, module})
        types_server(used, types, module, subs)

      {:check_var, var, pid} ->
        if !Enum.member?(used, var) do
          type = Map.get(types, String.to_atom(var))

          if(type == nil) do
            raise "Could not find type for variable #{var}. Please declare it using \"var #{var} type\""
          end

          send(pid, {:type, type})
          types_server([var | used], types, module, subs)
        else
          send(pid, {:alredy_declared})
          types_server(used, types, module, subs)
        end

      {:check_return, pid} ->
        send(pid, Map.get(types, :return))
        types_server(used, types, module, subs)

      {:check_fun, name, pid} ->
        send(pid, {:fun_info, Map.get(subs, name)})
        types_server(used, types, module, subs)

      {:kill} ->
        :ok
    end
  end

  # ------------------------------ NIF Stubs ------------------------------
  @impl PolyHok.BackendBehaviour
  def new_empty_gpu_array_nif(_l, _c, _type) do
    :erlang.nif_error(:nif_not_loaded)
  end

  @impl PolyHok.BackendBehaviour
  def new_gpu_array_from_nx_nif(_nx, _l, _c, _type) do
    :erlang.nif_error(:nif_not_loaded)
  end

  @impl PolyHok.BackendBehaviour
  def get_gpu_array_nif(_gnx, _l, _c, _type) do
    :erlang.nif_error(:nif_not_loaded)
  end

  @impl PolyHok.BackendBehaviour
  def synchronize_nif() do
    :erlang.nif_error(:nif_not_loaded)
  end

  @impl PolyHok.BackendBehaviour
  def jit_compile_nif(_kernel_name, _kernel_code) do
    :erlang.nif_error(:nif_not_loaded)
  end

  @impl PolyHok.BackendBehaviour
  def jit_launch_nif(_kernel_resource, _blocks, _threads, _len_args, _types_args, _args) do
    :erlang.nif_error(:nif_not_loaded)
  end
end
