defmodule PolyHokFunctions do
  defguard is_atomic_type(t) when t in [:tatomic_int, :tatomic_float, :tatomic_double]

  # The functions_lookup map is used to store the name, return type, argument types and the generated OpenCL name
  # of Orchestra DSL built-in functions. If the function does not have a different name in OpenCL, you can leave
  # the opencl_name field as nil, and it will be generated by the backend using the function name.
  @functions_lookup %{
    get_global_id: %{
      return_type: :int,
      arg_types: [:int]
    },
    get_global_size: %{
      return_type: :int,
      arg_types: [:int]
    },
    get_local_id: %{
      return_type: :int,
      arg_types: [:int]
    },
    get_local_size: %{
      return_type: :int,
      arg_types: [:int]
    },
    get_group_id: %{
      return_type: :int,
      arg_types: [:int]
    },
    get_num_groups: %{
      return_type: :int,
      arg_types: [:int]
    },
    sqrt: %{
      return_type: :float,
      arg_types: [:float]
    },
    sqrtf: %{
      return_type: :float,
      arg_types: [:float],
      opencl_name: "sqrt"
    },
    max: %{
      return_type: :float,
      arg_types: [:float, :float]
    },
    fmaxf: %{
      return_type: :float,
      arg_types: [:float, :float]
    },
    min: %{
      return_type: :float,
      arg_types: [:float, :float]
    },
    fminf: %{
      return_type: :float,
      arg_types: [:float, :float]
    },
    cas_int: %{
      return_type: :int,
      arg_types: [:tint, :int, :int]
    },
    cas_float: %{
      return_type: :float,
      arg_types: [:tfloat, :float, :float]
    },
    cas_double: %{
      return_type: :double,
      arg_types: [:tdouble, :double, :double]
    },
    sin: %{
      return_type: :float,
      arg_types: [:float]
    },
    cos: %{
      return_type: :float,
      arg_types: [:float]
    },
    tan: %{
      return_type: :float,
      arg_types: [:float]
    },
    exp: %{
      return_type: :float,
      arg_types: [:float]
    },
    log: %{
      return_type: :float,
      arg_types: [:float]
    },
    pow: %{
      return_type: :float,
      arg_types: [:float, :float]
    },
    trunc: %{
      return_type: :int,
      arg_types: [:float]
    },
    abs: %{
      return_type: :int,
      arg_types: [:int]
    },
    fabs: %{
      return_type: :float,
      arg_types: [:float]
    },
    fmod: %{
      return_type: :float,
      arg_types: [:float, :float]
    },
    clamp: %{
      return_type: :float,
      arg_types: [:float, :float, :float]
    },
    __syncthreads: %{
      return_type: :unit,
      arg_types: []
    },
    # --- Atomics ---
    init_atomic_int: %{
      return_type: :unit,
      arg_types: [:tatomic_int, :int],
    },
    init_atomic_float: %{
      return_type: :unit,
      arg_types: [:tatomic_float, :float],
    },
    init_atomic_double: %{
      return_type: :unit,
      arg_types: [:tatomic_double, :double],
    },
    load_atomic_int: %{
      return_type: :int,
      arg_types: [:tatomic_int],
    },
    # ---- This one is here just to demonstrate how stupid libSPIRV is. It thinks, because of the function 'atomic_' prefix,
    # that this function is a built-in OpenCL C atomic function. This makes the ENTIRE Erlang BEAM VM to crash :D
    # This stupid idiot compiler took me 2hrs to debug. - Henrique
    atomic_load_int: %{
      return_type: :int,
      arg_types: [:tatomic_int],
    },
    # ----
    load_atomic_float: %{
      return_type: :float,
      arg_types: [:tatomic_float],
    },
    load_atomic_double: %{
      return_type: :double,
      arg_types: [:tatomic_double],
    },
    add_atomic_int: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    add_atomic_float: %{
      return_type: :float,
      arg_types: [:tatomic_float, :float],
    },
    add_atomic_double: %{
      return_type: :double,
      arg_types: [:tatomic_double, :double],
    },
    sub_atomic_int: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    sub_atomic_float: %{
      return_type: :float,
      arg_types: [:tatomic_float, :float],
    },
    sub_atomic_double: %{
      return_type: :double,
      arg_types: [:tatomic_double, :double],
    },
    exchange_atomic_int: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    exchange_atomic_float: %{
      return_type: :float,
      arg_types: [:tatomic_float, :float],
    },
    exchange_atomic_double: %{
      return_type: :double,
      arg_types: [:tatomic_double, :double],
    },
    min_atomic_int: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    min_atomic_float: %{
      return_type: :float,
      arg_types: [:tatomic_float, :float],
    },
    min_atomic_double: %{
      return_type: :double,
      arg_types: [:tatomic_double, :double],
    },
    max_atomic_int: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    max_atomic_float: %{
      return_type: :float,
      arg_types: [:tatomic_float, :float],
    },
    max_atomic_double: %{
      return_type: :double,
      arg_types: [:tatomic_double, :double],
    },
    and_atomic: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    or_atomic: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    xor_atomic: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    }
  }

  # Create a lookup function clause for each function in the functions_lookup map
  for {fun_name, info} <- @functions_lookup do
    def lookup(unquote(fun_name)) do
      unquote(Macro.escape(info))
    end

    def exists?(unquote(fun_name)) do
      true
    end
  end

  # Clauses when the function is not found in the lookup
  def lookup(_fun) do
    nil
  end

  def exists?(_fun) do
    false
  end
end
